version: "3.8"

services:
  app:
    build: ./
    container_name: restapi
    hostname: restapi
    ports:
      - "9000:9000"
    depends_on:
      - data-base
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}

  data-base:
    restart: always
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_NAME=${PG_NAME}
